# Generated by Django 3.1.14 on 2025-04-13 11:06

import corm.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overrides', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            bases=(models.Model, corm.models.ManagementPermissionMixin),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company/Organization Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email Address')),
            ],
        ),
    ]
