# Generated by Django 3.2.25 on 2025-04-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corm', '0001_initial'),
        ('djstripe', '0010_alter_customer_balance'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='communities',
            field=models.ManyToManyField(through='billing.Management', to='corm.Community'),
        ),
        migrations.AddField(
            model_name='organization',
            name='customer',
            field=models.ForeignKey(blank=True, help_text="The team's Stripe Customer object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.customer'),
        ),
        migrations.AddField(
            model_name='management',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_management', to='corm.community'),
        ),
        migrations.AddField(
            model_name='management',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.organization'),
        ),
        migrations.AddField(
            model_name='management',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The team's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.subscription'),
        ),
    ]
